### ISSUE TITLE
Simplify the CSS for the font-weight property.

### ISSUE THREAD

**Issue by josephtkim** [mthom26/prj-rev-bwfs-dasmoto#6]
It is a good idea to try and simplify the CSS code as much as possible to make the code cleaner and to remove repetitive code. You did a great job with this, but you can simplify it further for the font-weight property as well. You might do this like so,

```css
h1, h2, #bluetext {
  font-weight: bold;
}
```
